/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alessandromarin' at '7/30/16 6:38 PM' with Gradle 2.14
 *
 * @author alessandromarin, @date 7/30/16 6:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
